app:
  version: 1.0.1
  schedule:
    file-synchronize: true
    check-last-send-file: true
    check-space-on-disc: true
    download-file-from-dahua: false
    check-timezone: false
  ssh:
    username: xxxxxxxx
    password: xxxxxxxx
    host: xx.xx.xx.xx
    port: 22
  ftp:
    host: 31.130.96.114
    port: 2121
server:
  port: 7207
  error:
    include-message: always

logging:
  level:
    ROOT: INFO
    com:
      siseth:
        adapter: DEBUG
    org:
      hibernate:
        SQL: INFO
  file:
    name: logs/adapter.log

springdoc:
  api-docs:
    path: /api/digital/source-adapter/v3/api-docs

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  application:
    name: source-adapter-service
  datasource:
    url: jdbc:postgresql://10.0.5.230:5432/sourceAdapter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      database: postgresql
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Europe/Warsaw

