ALTER TABLE source."D_IMAGE_SOURCE" ADD COLUMN IF NOT EXISTS "dateNameRegex" VARCHAR(255);

ALTER TABLE source."D_IMAGE_SOURCE" ADD COLUMN IF NOT EXISTS "synchronize" BOOLEAN DEFAULT FALSE;

ALTER TABLE source."D_IMAGE_SOURCE" ADD COLUMN IF NOT EXISTS "synchronizedAt" TIMESTAMP WITH TIME ZONE;

ALTER TABLE source."D_IMAGE_SOURCE" ADD COLUMN IF NOT EXISTS "deviceType" VARCHAR(255);

ALTER TABLE source."D_IMAGE_SOURCE" ADD COLUMN IF NOT EXISTS "lastPhotoUploadAt" TIMESTAMP WITH TIME ZONE;
